website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String(100))
    name = db.Column(db.String(100))
    teacher_id = db.Column(db.Integer, db.ForeignKey('teacher.id'))
    

class Teacher(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    UUID = db.Column(db.String(100), unique=True)
    title_before = db.Column(db.String(20))
    first_name = db.Column(db.String(20))
    middle_name = db.Column(db.String(20))
    last_name = db.Column(db.String(20))
    title_after = db.Column(db.String(20))
    picture_url = db.Column(db.String(200))
    location = db.Column(db.String(50)) 
    claim = db.Column(db.String(100))
    bio = db.Column(db.String(1000))
    
    price_per_hour = db.Column(db.Integer)
    
    
    
    
class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    telephone_numbers = db.Column(db.String(100))
    emails = db.Column(db.String(100))
    teacher_id = db.Column(db.Integer, db.ForeignKey('teacher.id'))
    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager



db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
        app = Flask(__name__)
        app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
        app.config['UPLOAD_FOLDER'] = 'static/files'
        app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
        db.init_app(app)
        

        
        

        from .views import views
        from .auth import auth
        from .api import api

        app.register_blueprint(views, url_prefix='/')
        app.register_blueprint(auth, url_prefix='/')
        app.register_blueprint(api, url_prefix='/api')

        from .models import Tag, Teacher, Contact
        
        with app.app_context():
                create_database(app)
        
        
        
        return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all()
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Tag, Teacher, Contact
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

website/routes.py
# app/routes.py
from flask import jsonify
from flask_restful import Api, Resource, reqparse
from app.models import Teacher, db

api = Api(app)

class LecturersResource(Resource):
    def get(self):
        lecturers = Teacher.query.all()
        return jsonify([{ "first_name": lecturer.first_name, "last_name": lecturer.last_name, "UUID": lecturer.UUID} for lecturer in lecturers])


    def post(self):
        parser = reqparse.RequestParser()
        parser.add_argument('first_name', type=str, required=True)
        parser.add_argument('last_name', type=str, required=True)
        parser.add_argument('UUID', type=str, required=True)

        args = parser.parse_args()

        lecturer = Teacher(first_name=args['first_name'], last_name=args['last_name'], UUID=args['UUID'])
        db.session.add(lecturer)
        db.session.commit()

        return jsonify({"first_name": lecturer.first_name, "last_name": lecturer.last_name, "UUID": lecturer.UUID}), 201


api.add_resource(LecturersResource, '/lecturers')

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask import Flask
from pathlib import Path
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from flask_login import login_user, login_required, logout_user, current_user
from .models import Tag, Teacher, Contact
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
import os
import shutil
from . import db, create_app
from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField
from base64 import b64encode
import json
import codecs



views = Blueprint('views', __name__)

app = Flask(__name__)
app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
app.config['UPLOAD_FOLDER'] = 'static/files'

api = Blueprint('api', __name__)

def load_json_data(file_path):
    with codecs.open(file_path, 'r', 'utf-8') as file:
        data = json.load(file)
        # Explicitly encode string values to UTF-8
        if isinstance(data, dict):
            data = {k: v.encode('utf-8').decode('utf-8') if isinstance(v, str) else v for k, v in data.items()}
            
        
        return data
def listToString(s):
 
    # initialize an empty string
    str1 = " "
 
    # return string
    return (str1.join(s))

def save_json_data(data):
    print(listToString(data.get("contact", {}).get("telephone_numbers", [])))
    teacher = Teacher(
        UUID=data.get("UUID"),
        title_before=data.get("title_before"),
        first_name=data.get("first_name"),
        middle_name=data.get("middle_name"),
        last_name=data.get("last_name"),
        title_after=data.get("title_after"),
        picture_url=data.get("picture_url"),
        location=data.get("location"),
        claim=data.get("claim"),
        bio=data.get("bio"),
        price_per_hour=data.get("price_per_hour")
    )
    tags = [Tag(uuid=tag["uuid"], name=tag["name"]) for tag in data.get("tags", [])]
    teacher.tags = tags
    
    telephone_numbers=listToString(data.get("contact", {}).get("telephone_numbers", []))
    emails=listToString(data.get("contact", {}).get("emails", []))
     
    contact = Contact(telephone_numbers = telephone_numbers, emails = emails, teacher_id= data.get("UUID"))
    db.session.add(teacher)
    db.session.add(contact)
    db.session.commit()
    
def get_teacher_by_uuid(uuid):
    teacher = Teacher.query.filter_by(UUID=uuid).first()
    return teacher

def get_contact_by_uuid(uuid):
    contact = Contact.query.filter_by(teacher_id=uuid).first()
    
    return contact


@views.route('/', methods=['GET', 'POST'])
def home():
    # Get the list of all lecturers from the database
    all_lecturers = Teacher.query.all()
  
    return render_template("home.html", user=current_user, lecturers=all_lecturers)

@views.route('/lecturer/<uuid>', methods=['GET', 'POST'])

def profile(uuid):
    teacher = get_teacher_by_uuid(uuid)
    contact = get_contact_by_uuid(uuid)
   
    return render_template('lecturer.html', teacher=teacher, contact=contact)





  

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css')}}">
        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body>
        
            
               
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-item nav-link" id="home" href="/">Test</a>
                </li>
               
               
               
                <li class="nav-item dropdown pf1">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="pf2" src="/static/files/img/{{user.Profile_pic or 'zaklad.png'}}" width="40" height="40">
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" id="profile" href="/lecturer">Profil</a>
                
                </div>
                </li>
                </ul>
                </nav>
            



        
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}
        <br>
        <div class="container">
        {% block content %}
        {% endblock %}    
        </div>
        {% block body %} {% endblock %}
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
        <script type="text/javascript" src="{{ url_for('static', filename='sketch.js')}}"></script>
    </body>
</html>

website/templates/home.html
<!-- home.html -->

<!DOCTYPE html>
<html>
<head>
    <!-- Add your head content here -->
</head>
<body>
    <!-- Display a list of lecturers with links -->
    <ul>
        {% for lecturer in lecturers %}
            <li>
                <a href="{{ url_for('views.profile', uuid=lecturer.t_uuid) }}">
                    {{ lecturer.first_name }} {{ lecturer.last_name }}
                </a>
                {{ lecturer.claim }}
                
                <img class="profile" src="{{ lecturer.picture_url }}" alt="Obrázek lektora">
                
                <ul>
                    {% for tag in lecturer.tags %}
                        <li>{{ tag.name }}</li>
                    {% endfor %}
                </ul>
                
                {{ lecturer.location }}
                {{ lecturer.price_per_hour }}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

website/templates/lecturer.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ teacher.first_name }} {{ teacher.last_name }} - Profil lektora</title>
    <link rel="stylesheet" href="CSS_TdA.css">
</head>
<body style="background-color:#74C7D3">

    <p>{{ teacher.title_before }} {{ teacher.first_name }} {{ teacher.middle_name }} {{ teacher.last_name }} {{ teacher.title_after }}</p>

    <img class="profile" src="{{ teacher.picture_url }}" alt="Obrázek lektora">

    <p>Místo: {{ teacher.location }}</p>
    <p>Prohlášení: {{ teacher.claim }}</p>
    <p>Životopis: {{ teacher.bio }}</p>

    <ul>
        {% for tag in teacher.tags %}
            <li>{{ tag.name }}</li>
        {% endfor %}
    </ul>
    <p> {{price_per_hour}}            </p>
    <p>Telefonní čísla: {{ contact.telephone_numbers }}</p>
    <p>Emaily: {{ contact.emails }}</p>

</body>
</html>